package constants

// order status
const (
	ORDER_STATUS_NEW       = "NEW"
	ORDER_STATUS_CONFIRMED = "CONFIRMED"
	ORDER_STATUS_DELIVERED = "DELIVERED"
	ORDER_STATUS_COMPLETED = "COMPLETED"
	ORDER_STATUS_CANCELLED = "CANCELLED"
)

// fulfillmentstatus
const (
	FULFILLMENT_STATUS_FULFILLED           = "FULFILLED"
	FULFILLMENT_STATUS_UNFULFILLED         = "UNFULFILLED"
	FULFILLMENT_STATUS_PATRIAL_FULFILLED   = "PATRIAL_FULFILLED"
	FULFILLMENT_STATUS_REDUNDANT_FULFILLED = "REDUNDANT_FULFILLED"
)

// payment status
const (
	PAYMENT_STATUS_PAID           = "PAID"
	PAYMENT_STATUS_UNPAID         = "UNPAID"
	PAYMENT_STATUS_PATRIAL_PAID   = "PATRIAL_PAID"
	PAYMENT_STATUS_REDUNDANT_PAID = "REDUNDANT_PAID"
)
